
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// For local development, these will be listed as "API URL" and "anon key" when starting supabase in Docker.  
// To connect your own Supabase project:
// 1. Replace SUPABASE_URL with your project's API URL
// 2. Replace SUPABASE_PUBLISHABLE_KEY with your project's anon key
// You can find these in your Supabase project settings under API

// Fallback values for development - replace with your actual Supabase credentials
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDQ5NzQwNzQsImV4cCI6MTk2MDU1MDA3NH0.placeholder";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
