// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkvtnyvttgjiherassmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdnRueXZ0dGdqaWhlcmFzc21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzkxNzcsImV4cCI6MjA3MTkxNTE3N30.8LovbABQbDqSkVzWrqr6WnCZawP2V7aFM0-htaounI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});