
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// For local development, these will be listed as "API URL" and "anon key" when starting supabase in Docker.  
// To connect your own Supabase project:
// 1. Replace SUPABASE_URL with your project's API URL
// 2. Replace SUPABASE_PUBLISHABLE_KEY with your project's anon key
// You can find these in your Supabase project settings under API
const SUPABASE_URL = "[YOUR_SUPABASE_PROJECT_URL]"; // Replace with your project's API URL
const SUPABASE_PUBLISHABLE_KEY = "[YOUR_SUPABASE_ANON_KEY]"; // Replace with your project's anon key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
